    mov ax,bx
    mov bx,cx
    mov bx,ax
    mov ax,data
    mov data,ax
    mov cx,data
    mov data,cx
    mov al,bl
    mov bl,cl
    mov bl,al
    mov al,other
    mov other,al
    mov cl,other
    mov other,cl
    add ax,bx
    add bx,cx
    add bx,ax
    add ax,data
    add data,ax
    add cx,data
    add data,cx
    add al,bl
    add bl,cl
    add bl,al
    add al,other
    add other,al
    add cl,other
    add other,cl
    sub ax,bx
    sub bx,cx
    sub bx,ax
    sub ax,data
    sub data,ax
    sub cx,data
    sub data,cx
    sub al,bl
    sub bl,cl
    sub bl,al
    sub al,other
    sub other,al
    sub cl,other
    sub other,cl
    data dw 1
    other db 1